### PR TITLE
Making ParameterHelper Immutable First

### PR DESCRIPTION
**Pull request by AndyM84**
Changed up the `ParameterHelper` class to be immutable, swapped out `add()` and `remove()` functionality for more common `with*` and `without*` methods.  Tests pass w/ 100% coverage, updated basic documentation as a placeholder for now.

### CODE REVIEW

**Comment by c-butcher** [comment]
I'm intrigued. What exactly is the end goal?

**Comment by AndyM84** [comment]
@c-butcher, I think the main motivation here is that I've found I mostly only use this to deal with predefined stacks such as `$_POST` or `$_GET`.  As a result, the default state for the `ParameterHelper` is one we want to preserve.  Following common convention from interfaces such as PSR-7 (the `withParameter()` and `withoutParameter()` stuff), we can consider the state of a `ParameterHelper` to be immutable, but still functionally something you can modify to your needs via cloning.

**Comment by mhykes** [comment]
I had to go look up the PSR-7 stuff, since I personally have been working almost exclusively with JS for the past couple of years.  It makes sense for the ParameterHelper to follow the PSR-7 standard since that is most likely what developers will be expecting at this point.  Having to call a function like withWhatever() or withoutWhatever() in order to get a modified version of the underlying object makes it more clear that the object you are working with has been modified.  In an express js middleware stack, where you just get handed a req and a res, it is a mystery where most of the contents of those two objects came from, and any work your middleware is doing on those objects is sure to be just as mysterious.  At least with PSR-7 rules, a developer is unlikely to accidentally modify the state of the parameter helper object they received.  In order to return a modified object, they will have to create a new object with the modifications and return that.

**Comment by AndyM84** [comment]
@c-butcher, unless you have a fundamental disagreement, do you mind if we merge this and maybe we can start looking at other areas we should follow similar conventions?

**Pull request merged**
